server:
  port: 8888
spring:
  application:
    name: expense-tracker-config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sabrikayraatalay/expense-tracker-config-server.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "sabrikayraatalay"
          password: ${GIT_KEY}